#!/usr/bin/env bash

# Clean up merged git branches

BRANCHES=$(git branch -v | grep '\[gone\]' | cut -f3 -d ' ')
if [ -z "$BRANCHES" ]; then
	echo "No branches.";
	exit;
fi

echo Deleting branches:
echo
for branch in $BRANCHES; do
	echo "$branch"
done

echo
read -rp "Proceed? (y/n): " ANS
echo
if [[ "$ANS" =~ ^[Yy]$ ]]; then
	# shellcheck disable=SC2086
	git branch --delete $BRANCHES
	# shellcheck disable=SC2086
	#git push --delete origin $BRANCHES
fi
