#!/usr/bin/env bash

if [[ $(uname) == "Darwin" ]]; then
    FINDER="choose"
else
    FINDER="tofi"
fi

SEL=$(cd ~/.password-store && fd --type f | $FINDER)

if [ -z "$SEL" ]; then
    exit
fi;

pass -c "${SEL//.gpg/}"
