#!/usr/bin/env bash


wifi_list() {
	#local WIFI_LIST='nmcli -f SSID,BARS,SECURITY,IN-USE'
	local WIFI_LIST='nmcli -f IN-USE,SSID device wifi'
	local SSID
	SSID=$($WIFI_LIST | awk 'NR!=1')

	echo "$SSID"
}
export -f wifi_list

SSID=$(printf '%s' "$(wifi_list)" | \
	fzf \
	--bind 'ctrl-r:reload(nmcli device wifi rescan; printf "$(wifi_list)")'\
	--header 'Refresh with CTRL-R'\
	| sed 's/^\*//g' # trim the in-use character
)

SSID_TRIMMED=$(echo "$SSID" | xargs)

if [ -z "$SSID" ]; then
	exit 1
fi

nmcli device wifi connect "$SSID_TRIMMED" &> /dev/null

if [[ "$?" -eq 0 ]]; then
	echo "Connected."
else
	echo "Failed. Attempting to get credentials."
	nmcli device wifi connect "$SSID_TRIMMED" --ask
fi
